In [ ]:
num=int(input("enter your digit:"))
sum=0
while num >0:
  digit=num%10
  sum += digit
  num=num//10
print("sum of digits",sum)


enter your digit:12345678
sum of digits 36


In [4]:
#str to int split int to str no split
n=list(map(int,input("enter a number:")))
add=list(map(lambda x :x+5,n))
print(add)


enter a number:1234
[6, 7, 8, 9]


In [9]:
listt=[1,2,3,4]
evennum=list(filter(lambda x:x%2==0,listt))
print(evennum)

[2, 4]


In [11]:
from functools import reduce
numbers=(1,2,3,4,5,6)
red=reduce(lambda x,y:x+y,numbers)
print(red)

21


In [13]:
#playing with class+objects
class car:
  brand="rolls"
  colour="red"
c1=car()
c1.brand
c1.colour
c1.brand


'rolls'

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0:2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
num=[1,2,3,4,5,6,7,88,888]
num[0:7:1]

[1, 2, 3, 4, 5, 6, 7]

In [ ]:

#Pass or Fail: Given marks in 3 subjects, print "Pass" if all  35, else "Fail"
t=int(input())

while t>0:
  chem=int(input("enter the student mark in chem"))
  maths=int(input("enter the student mark in maths"))
  eng=int(input("enter the student mark in eng"))
  if chem >= 35 and maths >= 35 and eng >= 35:
    print("pass")
  else:
    print("fail")

  t=-1

3
enter the student mark in chem36
enter the student mark in maths37
enter the student mark in eng38
pass


In [16]:
class car:
  def brand(self):
    print("toyota")
c1=car()
c1.brand()


toyota


In [23]:
class cars:
  def __init__(self,brand,color):
    self.brand=brand
    self.color=color
  def display(self):
      print(f"brand:{self.brand}and color:{self.color}")
c1=cars("rolls royce","dark red")
c2=cars("ferrari","red")
c1.display()

brand:rolls royceand color:dark red


In [ ]:
#reverse string
name=input("enter your name:")
print(name[::-1])

enter your name:lohith
htihol


In [ ]:
name=input("enter your name:")
reversed_name=name[::-1]
if reversed_name==name:
  print("it is palindrome ")
else:
  print("it is not a palindrome")

enter your name:madam
it is palindrome 


In [ ]:
name="qwerty"
vowels_count=0
for char in name:
  if char in "aeiou":
    vowels_count+=1
print(vowels_count)


1


In [ ]:
#3. Character Frequency: Input a string. Print the count of each character.
name=input("enter your name:")
frequency={}
for char in name:
  if char in frequency:
    frequency[char]+=1
  else:
    frequency[char]=1
for char,count in frequency.items():
   print(f"{char}:{count}")

enter your name:lohith
l:1
o:1
h:2
i:1
t:1


In [2]:
#count evn odd numbers
list1=list(map(int,input("enter numbers").split()))
even_count=0
odd_count=0
for i in list1:
  if i%2==0:
    even_count+=1
  else:
    odd_count+=1
print(even_count)
print(odd_count)

enter numbers1 2 3
1
2


In [12]:

listt=[1,2,3,4,5,6]
target=int(input("enter a number "))
print(listt.index(target))



enter a number 2
1


In [ ]:
list1=[1,2,3,4]
found= False
for i in list:
  if i==list1:
  found= True
  print("element is present")


In [ ]:
list1=list(input())
list1.sort()
print(list1[1])

23
3


In [ ]:
#ARMSTRONG NUMBER
num=int(input("enter a number:"))
sum=0
temp=num
n=len(str(num))
while temp>0:
  digit=temp%10
  sum +=digit**n
  temp=temp//10
if sum==num:
  print(f"{num} is an armstrong")
else:
  print("it is not armstrongnumber")

enter a number:9474
9474 is an armstrong


In [ ]:
#print second largest number
number=int(input("enter your number:"))
digits=[]
while number>0:
  digit=number%10
  digits.append(digit)
  number=number//10
elements=list(set(digits))
elements.sort(reverse=True)
if len(elements)>=2:
  print(elements[1])
else:
  print("there is no ")


enter your number:23
2


In [ ]:
t=int(input())
for _ in range(t):
  number=list(map(int,input("enter").split()))
  number.sort()
  print(number[1])


3
enter3 2 5
3
enter9 4 3 
4
enter9 3 5
5


In [ ]:
numbers=list(map(int,input("enter a number:").split()))
even_count=0
odd_count=0
for num in numbers:
  if num%2==0:
    even_count+=1
  else:
    odd_count+=1
print(even_count)
print(odd_count)#Count Even and Odd in List: Input a list of numbers. Count how many are even and odd.************************


enter a number:1 4 5 7
1
3


In [ ]:
#check if List is Sorted: Input a list. Check if it's sorted in ascending order
number=list(input())
num=number.sort()
if number==num:
  print("it is in ascending order")
else:
  print("it is nott")

1 2 3 4
it is nott


In [ ]:
#. Multiplication Table: Input a number. Print its multiplication table up to 10
num=int(input("enter a number "))
for i in range(11):
  table=num*i
  print(f"{num}*{i}={table}")

enter a number 23
23*0=0
23*1=23
23*2=46
23*3=69
23*4=92
23*5=115
23*6=138
23*7=161
23*8=184
23*9=207
23*10=230


In [ ]:
#. Count Digits: Input a number. Print how many digits it has
number=int(input("enter a number:"))
digits=[]
while number>0:
  digit=number%10
  digits.append(digit)
  number=number//10
count_digits=len(digits)
print("the digits in the number :",count_digits)


enter a number:32434434
the digits in the number : 8


In [ ]:
# Print All Even Numbers from 1 to N: Input N. Print even numbers from 1 to N
n=int(input("number a number:"))
for i in range(1,n+1):
  if i%2==0:
    print(i)

number a number:10
2
4
6
8
10


In [ ]:
#sum of First N Natural Numbers: Input N. Print 1 + 2 + ... + N
num=int(input("enter a number :"))
sum=0
while num>0:
  sum +=num
  num -=1
print(sum)


enter a number :5
15


In [ ]:
# 5. Factorial of a Number: Input a number. Output its factorial
number=int(input("enter a number "))
fact=1
while number > 1:
  fact *=number
  number-=1
print(fact)

enter a number 5
120


In [ ]:
number=int(input("enter a number "))
fact=1
for i in range(1,number+1):
  fact *=i
print(fact)

enter a number 5
120


In [ ]:
# Find Max in List: Input a list of numbers. Output the max value
data=list(input())
data.sort()
q=max(data)
maxvalue=data[-1]
print(maxvalue)
print(q)

1 2 3 4
4
4


In [ ]:
t=int(input())

while t>0:
  number=int(input("enter your number:"))
  number-=1
for i in range(11):
   table=number*i
  print(f"{number}*{i}={table}")
t-=1


IndentationError: unindent does not match any outer indentation level (<tokenize>, line 8)

In [ ]:
#out reverse
num=int(input("enter your digit:"))
reverse=0
while num>0:
  digit=num%10
  reverse=reverse*10+digit
  num=num//10
print(reverse)


enter your digit:987
789
